arch: s390x
services:
    - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOTTOKEN && docker build -f 1.14/alpine3.12/Dockerfile --tag quay.io/ibmz/golang:1.14 && docker push quay.io/ibmz/golang:1.14
