arch: s390x
services:
    - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOTTOKEN && cd 1.14/alpine3.12/ && docker build . --tag quay.io/ibmz/golang:1.14 && docker push quay.io/ibmz/golang:1.14
